version: '3'
services:
  mysql80:
    image: mysql:8.0
    container_name: coco-mysql
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: coco123456
    restart: always
  coco:
    build:
      context: coco
      dockerfile: Dockerfile
    container_name: coco-fe
    ports:
      - "8080:8080"
    volumes:
      - ./coco/storage:/storage
      - ./coco/logs:/logs
      - ./coco/backup:/backup
      - /etc/localtime:/etc/localtime
    depends_on:
      - mysql80
    restart: always